<p align="center">
<img align="center" width="600" src="../imgs/logo.png">
<h3 align="center">Introduction to Data Science</h3>
<h4 align="center">Chapter 0: Linear Algebra</h4>
<h5 align="center">Yam Peleg</h5>
</p>
<hr>

Many of the slides and notebooks in this repository are based on other repositories and tutorials. 

**References for this notebook:**  

* **[MJ Bahmani - 10 Steps to become a data scientist](https://www.kaggle.com/mjbahmani/10-steps-to-become-a-data-scientist)**
<hr>

### The Data

![](https://www.reno.gov/Home/ShowImage?id=7739&t=635620964226970000)

**Competition Description from Kaggle**  
With 79 explanatory variables describing (almost) every aspect of residential homes in Ames, Iowa, this competition challenges you to predict the final price of each home.

**Data description**  
This is a detailed description of the 79 features and their entries, quite important for this competition.  
You can download the txt file here: [**download**](https://www.kaggle.com/c/5407/download/data_description.txt)

 # <div style="text-align: center">Linear Algebra for Data Scientists 
<div style="text-align: center">
Having a basic knowledge of linear algebra is one of the requirements for any data scientist. In this tutorial we will try to cover all the necessary concepts related to linear algebra


<a id="1"></a> <br>
#  1-Introduction

we will cover following topic:
1. notation
1. Matrix Multiplication
1. Identity Matrix
1. Diagonal Matrix
1. Transpose of a Matrix
1. The Trace
1. Norms
1. Tensors
1. Hyperplane
1. Eigenvalues and Eigenvectors
## what is linear algebra?
**Linear algebra** is the branch of mathematics that deals with **vector spaces**. good understanding of Linear Algebra is intrinsic to analyze Machine Learning algorithms, especially for **Deep Learning** where so much happens behind the curtain.

<img src='https://camo.githubusercontent.com/e42ea0e40062cc1e339a6b90054bfbe62be64402/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3339313937313830393536333530383733382f3434323635393336333534333331383532382f7363616c61722d766563746f722d6d61747269782d74656e736f722e706e67' >

 <a id="top"></a> <br>

<a id="11"></a> <br>
## 1-1 Import

In [1]:
import matplotlib.patches as patch
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import glob
import sys
import os

from scipy.stats import norm
from scipy import linalg
from numpy import poly1d
from sklearn import svm

<a id="12"></a> <br>
##  1-2 Setup

In [2]:
%matplotlib inline
%precision 4
plt.style.use('ggplot')
np.set_printoptions(suppress=True)

<a id="2"></a> <br>
# 2- What is Linear Algebra?
Linear algebra is the branch of mathematics concerning linear equations such as
<img src='https://wikimedia.org/api/rest_v1/media/math/render/svg/f4f0f2986d54c01f3bccf464d266dfac923c80f3'>
Linear algebra is central to almost all areas of mathematics. 

<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Linear_subspaces_with_shading.svg/800px-Linear_subspaces_with_shading.svg.png'>


In [3]:
#3-dimensional vector in numpy
a = np.zeros((2, 3, 4))
    #l = [[[ 0.,  0.,  0.,  0.],
    #      [ 0.,  0.,  0.,  0.],
    #     [ 0.,  0.,  0.,  0.]],
    #     [[ 0.,  0.,  0.,  0.],
    #      [ 0.,  0.,  0.,  0.],
    #     [ 0.,  0.,  0.,  0.]]]
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [4]:
# Declaring Vectors

x = [1, 2, 3]
y = [4, 5, 6]

print(type(x))

# This does'nt give the vector addition.
print(x + y)

# Vector addition using Numpy

z = np.add(x, y)
print(z)
print(type(z))

# Vector Cross Product
mul = np.cross(x, y)
print(mul)

<class 'list'>
[1, 2, 3, 4, 5, 6]
[5 7 9]
<class 'numpy.ndarray'>
[-3  6 -3]


## 2-1 What is Vectorization?
In mathematics, especially in linear algebra and matrix theory, the vectorization of a matrix is a linear transformation which converts the matrix into a column vector. Specifically, the vectorization of an m × n matrix A, denoted vec(A), is the mn × 1 column vector obtained by stacking the columns of the matrix A on top of one another:
<img src='https://wikimedia.org/api/rest_v1/media/math/render/svg/30ca6a8b796fd3a260ba3001d9875e990baad5ab'>
[wikipedia](https://en.wikipedia.org/wiki/Vectorization_(mathematics) )

Vectors of the length $n$ could be treated like points in $n$-dimensional space. One can calculate the distance between such points using measures like [Euclidean Distance](https://en.wikipedia.org/wiki/Euclidean_distance). The similarity of vectors could also be calculated using [Cosine Similarity](https://en.wikipedia.org/wiki/Cosine_similarity).
###### [Go to top](#top)


## 3- Notation

<img src='http://s8.picofile.com/file/8349058626/la.png'>
[linear.ups.edu](http://linear.ups.edu/html/notation.html)

<a id="4"></a> <br>
## 4- Matrix Multiplication
<img src='https://www.mathsisfun.com/algebra/images/matrix-multiply-constant.gif'>

[mathsisfun](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

The result of the multiplication of two matrixes $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times p}$ is the matrix:

In [5]:
# initializing matrices 
x = np.array([[1, 2], [4, 5]]) 
y = np.array([[7, 8], [9, 10]])

$C = AB \in \mathbb{R}^{m \times n}$

That is, we are multiplying the columns of $A$ with the rows of $B$:

$C_{ij}=\sum_{k=1}^n{A_{ij}B_{kj}}$
<img src='https://cdn.britannica.com/06/77706-004-31EE92F3.jpg'>
[reference](https://cdn.britannica.com/06/77706-004-31EE92F3.jpg)

The number of columns in $A$ must be equal to the number of rows in $B$.

###### [Go to top](#top)

In [6]:
# using add() to add matrices 
print ("The element wise addition of matrix is : ") 
print (np.add(x,y))

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]


In [7]:
# using subtract() to subtract matrices 
print ("The element wise subtraction of matrix is : ") 
print (np.subtract(x,y))

The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]


In [8]:
# using divide() to divide matrices 
print ("The element wise division of matrix is : ") 
print (np.divide(x,y))

The element wise division of matrix is : 
[[0.1429 0.25  ]
 [0.4444 0.5   ]]


In [9]:
# using multiply() to multiply matrices element wise 
print ("The element wise multiplication of matrix is : ") 
print (np.multiply(x,y))

The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]


<a id="41"></a> <br>
## 4-1 Vector-Vector Products

numpy.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)[source]
Return the cross product of two (arrays of) vectors.[scipy](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.cross.html)
<img src='http://gamedevelopertips.com/wp-content/uploads/2017/11/image8.png'>
[image-gredits](http://gamedevelopertips.com)

In [10]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

We define the vectors $x$ and $y$ using *numpy*:

In [11]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print("x:", x)
print("y:", y)

x: [1 2 3 4]
y: [5 6 7 8]


We can now calculate the $dot$ or $inner product$ using the *dot* function of *numpy*:

In [12]:
np.dot(x, y)

70

The order of the arguments is irrelevant:

In [13]:
np.dot(y, x)

70

Note that both vectors are actually **row vectors** in the above code. We can transpose them to column vectors by using the *shape* property:

In [14]:
print("x:", x)
x.shape = (4, 1)
print("xT:", x)
print("y:", y)
y.shape = (4, 1)
print("yT:", y)

x: [1 2 3 4]
xT: [[1]
 [2]
 [3]
 [4]]
y: [5 6 7 8]
yT: [[5]
 [6]
 [7]
 [8]]


In fact, in our understanding of Linear Algebra, we take the arrays above to represent **row vectors**. *Numpy* treates them differently.

We see the issues when we try to transform the array objects. Usually, we can transform a row vector into a column vector in *numpy* by using the *T* method on vector or matrix objects:
###### [Go to top](#top)

In [15]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print("x:", x)
print("y:", y)
print("xT:", x.T)
print("yT:", y.T)

x: [1 2 3 4]
y: [5 6 7 8]
xT: [1 2 3 4]
yT: [5 6 7 8]


The problem here is that this does not do, what we expect it to do. It only works, if we declare the variables not to be arrays of numbers, but in fact a matrix:

In [16]:
x = np.array([[1, 2, 3, 4]])
y = np.array([[5, 6, 7, 8]])
print("x:", x)
print("y:", y)
print("xT:", x.T)
print("yT:", y.T)

x: [[1 2 3 4]]
y: [[5 6 7 8]]
xT: [[1]
 [2]
 [3]
 [4]]
yT: [[5]
 [6]
 [7]
 [8]]


Note that the *numpy* functions *dot* and *outer* are not affected by this distinction. We can compute the dot product using the mathematical equation above in *numpy* using the new $x$ and $y$ row vectors:
###### [Go to top](#top)

In [17]:
print("x:", x)
print("y:", y.T)
np.dot(x, y.T)

x: [[1 2 3 4]]
y: [[5]
 [6]
 [7]
 [8]]


array([[70]])

Or by reverting to:

In [18]:
print("x:", x.T)
print("y:", y)
np.dot(y, x.T)

x: [[1]
 [2]
 [3]
 [4]]
y: [[5 6 7 8]]


array([[70]])

To read the result from this array of arrays, we would need to access the value this way:

In [19]:
np.dot(y, x.T)[0][0]

70

<a id="42"></a> <br>
## 4-2 Outer Product of Two Vectors
Compute the outer product of two vectors.

In [20]:
x = np.array([[1, 2, 3, 4]])
print("x:", x)
print("xT:", np.reshape(x, (4, 1)))
print("xT:", x.T)
print("xT:", x.transpose())

x: [[1 2 3 4]]
xT: [[1]
 [2]
 [3]
 [4]]
xT: [[1]
 [2]
 [3]
 [4]]
xT: [[1]
 [2]
 [3]
 [4]]


Example
###### [Go to top](#top)

We can now compute the **outer product** by multiplying the column vector $x$ with the row vector $y$:

In [21]:
x = np.array([[1, 2, 3, 4]])
y = np.array([[5, 6, 7, 8]])
x.T * y

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

*Numpy* provides an *outer* function that does all that:

In [22]:
np.outer(x, y)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

Note, in this simple case using the simple arrays for the data structures of the vectors does not affect the result of the *outer* function:

In [23]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
np.outer(x, y)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

<a id="43"></a> <br>
## 4-3 Matrix-Vector Products
Use numpy.dot or a.dot(b). See the documentation [here](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html).

In [24]:
a = np.array([[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]])
b = np.array([1, 2, 3])
print (a.dot(b))

[16  6  8]


Using *numpy* we can compute $Ax$:

In [25]:
A = np.array([[4, 5, 6],
             [7, 8, 9]])
x = np.array([1, 2, 3])
A.dot(x)

array([32, 50])

<a id="44"></a> <br>
## 4-4 Matrix-Matrix Products

In [26]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [27]:
matrix1 = np.matrix(a)
matrix2 = np.matrix(b)

In [28]:
matrix1 + matrix2

matrix([[5, 1],
        [2, 3]])

In [29]:
matrix1 - matrix2

matrix([[-3, -1],
        [-2, -1]])

<a id="441"></a> <br>
### 4-4-1  Multiplication

In [30]:
np.dot(matrix1, matrix2)

matrix([[4, 1],
        [2, 2]])

In [31]:
matrix1 * matrix2

matrix([[4, 1],
        [2, 2]])

<a id="5"></a> <br>
## 5- Identity Matrix

numpy.identity(n, dtype=None)

Return the identity array.
[source](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.identity.html)

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

How to create *identity matrix* in *numpy*  

In [33]:
identy = np.array([[21, 5, 7],[9, 8, 16]])
print("identy:", identy)

identy: [[21  5  7]
 [ 9  8 16]]


In [34]:
identy.shape

(2, 3)

In [35]:
np.identity(identy.shape[1], dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
np.identity(identy.shape[0], dtype="int")

array([[1, 0],
       [0, 1]])

<a id="51"></a> <br>
### 5-1  Inverse Matrices

In [37]:
inverse = np.linalg.inv(matrix1)
print(inverse)

[[1. 0.]
 [0. 1.]]


<a id="6"></a> <br>
## 6- Diagonal Matrix

In *numpy* we can create a *diagonal matrix* from any given matrix using the *diag* function:

In [38]:
import numpy as np
A = np.array([[0,   1,  2,  3],
              [4,   5,  6,  7],
              [8,   9, 10, 11],
              [12, 13, 14, 15]])
np.diag(A)

array([ 0,  5, 10, 15])

In [39]:
np.diag(A, k=1)

array([ 1,  6, 11])

In [40]:
np.diag(A, k=-1)

array([ 4,  9, 14])

<a id="7"></a> <br>
## 7- Transpose of a Matrix
For reading about Transpose of a Matrix, you can visit [this link](https://py.checkio.org/en/mission/matrix-transpose/)

In [41]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [42]:
a.transpose()

array([[1, 3],
       [2, 4]])

<a id="8"></a> <br>
## 8- Symmetric Matrices
In linear algebra, a symmetric matrix is a square matrix that is equal to its transpose. Formally,
<img src='https://wikimedia.org/api/rest_v1/media/math/render/svg/ad8a5a3a4c95de6f7f50b0a6fb592d115fe0e95f'>

[wikipedia](https://en.wikipedia.org/wiki/Symmetric_matrix)

In [43]:
N = 100
b = np.random.random_integers(-2000,2000,size=(N,N))
b_symm = (b + b.T)/2

e:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(-2000, 2000 + 1) instead
  


<a id="9"></a> <br>
## 9-The Trace
Return the sum along diagonals of the array.

In [44]:
np.trace(np.eye(3))

3.0

In [45]:
print(np.trace(matrix1))

2


In [46]:
det = np.linalg.det(matrix1)
print(det)

1.0


<a id="10"></a> <br>
# 10- Norms
numpy.linalg.norm
This function is able to return one of eight different matrix norms, or one of an infinite number of vector norms (described below), depending on the value of the ord parameter. [scipy](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.norm.html)

 <a id="top"></a> <br>

In [47]:
v = np.array([1,2,3,4])
norm.median(v)

array([1., 2., 3., 4.])

<a id="11"></a> <br>
# 11- Linear Independence and Rank
How to identify the linearly independent rows from a matrix?

In [48]:
#How to find linearly independent rows from a matrix
matrix = np.array(
    [
        [0, 1 ,0 ,0],
        [0, 0, 1, 0],
        [0, 1, 1, 0],
        [1, 0, 0, 1]
    ])

lambdas, V =  np.linalg.eig(matrix.T)
# The linearly dependent row vectors 
print (matrix[lambdas == 0,:])

[[0 1 1 0]]


<a id="12"></a> <br>
# 12-  Subtraction and Addition of Metrices

In [49]:
import numpy as np
print("np.arange(9):", np.arange(9))
print("np.arange(9, 18):", np.arange(9, 18))
A = np.arange(9, 18).reshape((3, 3))
B = np.arange(9).reshape((3, 3))
print("A:", A)
print("B:", B)

np.arange(9): [0 1 2 3 4 5 6 7 8]
np.arange(9, 18): [ 9 10 11 12 13 14 15 16 17]
A: [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
B: [[0 1 2]
 [3 4 5]
 [6 7 8]]


We can now add and subtract the two matrices $A$ and $B$:

In [50]:
A + B

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [51]:
A - B

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

<a id="121"></a> <br>
## 12-1 Inverse
We use numpy.linalg.inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.[tutorialspoint](https://www.tutorialspoint.com/numpy/numpy_inv.htm)

In [52]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x )
print (y )
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


<a id="13"></a> <br>
## 13- Orthogonal Matrices
How to create random orthonormal matrix in python numpy

In [53]:
## based on https://stackoverflow.com/questions/38426349/how-to-create-random-orthonormal-matrix-in-python-numpy
def rvs(dim=3):
     random_state = np.random
     H = np.eye(dim)
     D = np.ones((dim,))
     for n in range(1, dim):
         x = random_state.normal(size=(dim-n+1,))
         D[n-1] = np.sign(x[0])
         x[0] -= D[n-1]*np.sqrt((x*x).sum())
         # Householder transformation
         Hx = (np.eye(dim-n+1) - 2.*np.outer(x, x)/(x*x).sum())
         mat = np.eye(dim)
         mat[n-1:, n-1:] = Hx
         H = np.dot(H, mat)
         # Fix the last sign such that the determinant is 1
     D[-1] = (-1)**(1-(dim % 2))*D.prod()
     # Equivalent to np.dot(np.diag(D), H) but faster, apparently
     H = (D*H.T).T
     return H

<a id="14"></a> <br>
## 14- Range and Nullspace of a Matrix

In [54]:
from scipy.linalg import null_space
A = np.array([[1, 1], [1, 1]])
ns = null_space(A)
ns * np.sign(ns[0,0])  # Remove the sign ambiguity of the vector

array([[ 0.7071],
       [-0.7071]])

<a id="15"></a> <br>
# 15-  Determinant
Compute the determinant of an array

In [55]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

<a id="16"></a> <br>
# 16- Tensors

A [**tensor**](https://en.wikipedia.org/wiki/Tensor) could be thought of as an organized multidimensional array of numerical values. A vector could be assumed to be a sub-class of a tensor. Rows of tensors extend alone the y-axis, columns along the x-axis. The **rank** of a scalar is 0, the rank of a **vector** is 1, the rank of a **matrix** is 2, the rank of a **tensor** is 3 or higher.

###### [Go to top](#top)

In [56]:
# This part requires tensorflow
import tensorflow as tf

In [56]:
# credits: https://www.tensorflow.org/api_docs/python/tf/Variable
A = tf.Variable(np.zeros((5, 5), dtype=np.float32), trainable=False)
new_part = tf.ones((2,3))
update_A = A[2:4,2:5].assign(new_part)
sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
print(update_A.eval())

NameError: name 'tf' is not defined

<a id="25"></a> <br>
# 17- Hyperplane

The **hyperplane** is a sub-space in the ambient space with one dimension less. In a two-dimensional space the hyperplane is a line, in a three-dimensional space it is a two-dimensional plane, etc.

Hyperplanes divide an $n$-dimensional space into sub-spaces that might represent clases in a machine learning algorithm.

In [ ]:
##based on this address: https://stackoverflow.com/questions/46511017/plot-hyperplane-linear-svm-python
np.random.seed(0)
X = np.r_[np.random.randn(20, 2) - [2, 2], np.random.randn(20, 2) + [2, 2]]
Y = [0] * 20 + [1] * 20

fig, ax = plt.subplots()
clf2 = svm.LinearSVC(C=1).fit(X, Y)

# get the separating hyperplane
w = clf2.coef_[0]
a = -w[0] / w[1]
xx = np.linspace(-5, 5)
yy = a * xx - (clf2.intercept_[0]) / w[1]

# create a mesh to plot in
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx2, yy2 = np.meshgrid(np.arange(x_min, x_max, .2),
                     np.arange(y_min, y_max, .2))
Z = clf2.predict(np.c_[xx2.ravel(), yy2.ravel()])

Z = Z.reshape(xx2.shape)
ax.contourf(xx2, yy2, Z, cmap=plt.cm.coolwarm, alpha=0.3)
ax.scatter(X[:, 0], X[:, 1], c=Y, cmap=plt.cm.coolwarm, s=25)
ax.plot(xx,yy)

ax.axis([x_min, x_max,y_min, y_max])
plt.show()

<a id="31"></a> <br>
## 20- Exercises
let's do some exercise.

### 20-1 Create a dense meshgrid

In [ ]:
np.mgrid[0:5,0:5]

### 20-2 Permute array dimensions

In [ ]:
a=np.array([1,2,3])
b=np.array([(1+5j,2j,3j), (4j,5j,6j)])
c=np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]])

In [ ]:
np.transpose(b)

In [ ]:
b.flatten()

In [ ]:
np.hsplit(c,2)

## 20-3 Polynomials

In [ ]:
p=poly1d([3,4,5])
p

## SciPy Cheat Sheet: Linear Algebra in Python
This Python cheat sheet is a handy reference with code samples for doing linear algebra with SciPy and interacting with NumPy.

[DataCamp](https://www.datacamp.com/community/blog/python-scipy-cheat-sheet)